/**
  ******************************************************************************
  * @file     lib.c
  * @author   Auto-generated by STM32CubeIDE
  * @version  V1.0
  * @date     30/06/2025 17:11:08
  * @brief    Default under dev library file.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "gpio/gpio.h"

#ifndef __GPIO_H__
#define __GPIO_H__


#endif /* __GPIO_H__ */
