/**
  ******************************************************************************
  * @file     tim.h
  * @author   Auto-generated by STM32CubeIDE
  * @version  V1.0
  * @date     30/06/2025 17:11:08
  * @brief    Default under dev library file.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "tim/tim.h"
#include "tim/tim_pwm.h"

#ifndef __TIM_H__
#define __TIM_H__


#endif /* __GPIO_H__ */
