/**
  ******************************************************************************
  * @file     customDriver.c
  * @author   Auto-generated by STM32CubeIDE
  * @version  V1.0
  * @date     30/06/2025 17:11:08
  * @brief    Default under dev library file.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "gpio/gpio.h"
#include "tim/tim.h"

/** Functions ----------------------------------------------------------------*/

void custom_test_gpio_timer(void) {
    // Example: Blink PB2 every 1 second using TIM2
    GPIO_ClockEnable(GPIO_B);
    GPIO_Init(GPIO_B, OUTPUT, PP, PIN_2);

    TIM_Init(TIM2_BASE, 16000 - 1, 1000 - 1); // 1s timer @16MHz
    TIM_Start(TIM2_BASE);

    while (1) {
        if (TIM_HasElapsed(TIM2_BASE)) {
            TIM_ClearFlag(TIM2_BASE);
            GPIO_ToggleBits(GPIO_B, GPIO_Pin_2);
        }
    }
}

